var _____WB$wombat$assign$function_____=function(name){return (globalThis._wb_wombat && globalThis._wb_wombat.local_init && globalThis._wb_wombat.local_init(name))||globalThis[name];};if(!globalThis.__WB_pmw){globalThis.__WB_pmw=function(obj){this.__WB_source=obj;return this;}}{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
(function(){var g=void 0,i=!0,j=null,n=!1,p=this,aa=function(a,b,c){a=a.split(".");c=c||p;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==g?c[d]=b:c=c[d]?c[d]:c[d]={}},ba=function(a,b){for(var c=a.split("."),d=b||p,e;e=c.shift();)if(d[e]!=j)d=d[e];else return j;return d},ca=function(){},da=function(a){a.getInstance=function(){return a.ra?a.ra:a.ra=new a}},ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof
Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},
s=function(a){return"array"==ea(a)},fa=function(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length},t=function(a){return"string"==typeof a},ga=function(a){return"number"==typeof a},ha=function(a){var b=typeof a;return"object"==b&&a!=j||"function"==b},ia="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ja=0,ka=function(a,b,c){return a.call.apply(a.bind,arguments)},la=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,
2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},u=function(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return u.apply(j,arguments)},ma=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}},v=function(a,b,c){aa(a,
b,c)},na=function(a,b,c){a[b]=c},oa=function(a,b){function c(){}c.prototype=b.prototype;a.Fa=b.prototype;a.prototype=new c;a.prototype.constructor=a};var w=function(a,b){var c=parseFloat(a);return isNaN(c)||1<c||0>c?b:c},pa=function(a,b){return/^true$/.test(a)?i:/^false$/.test(a)?n:b},qa=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,ra=function(a,b){if(!a)return b;var c=a.match(qa);return c?c[0]:b};var sa=w("0",0),ta=w("0",0),ua=w("0",0),va=w("0",0),wa=w("0",0),xa=w("0",0),ya=w("0.01",0),za=w("0.02",0),Aa=w("1",0),Ba=w("0.01",0),Ca=w("0.01",
0),Da=w("0.1",0),Ea=w("0.01",0);var Fa=function(){var a="r20130122";return a},Ha=pa("false",n),Ia=pa("false",n),Ja=pa("false",n),Ka=pa("false",n);var La={GOOGLEADS_G_DOUBLECLICK_NET:"googleads.g.doubleclick.net",GOOGLEADS2_G_DOUBLECLICK_NET:"googleads2.g.doubleclick.net",PAGEAD2_GOOGLESYNDICATION_COM:"pagead2.googlesyndication.com",PAGEAD2_GOOGLEADSERVICES_COM:"pagead2.googleadservices.com",PARTNER_GOOGLEADSERVICES_COM:"partner.googleadservices.com",PUBADS_G_DOUBLECLICK_NET:"pubads.g.doubleclick.net",SECUREPUBADS_G_DOUBLECLICK_NET:"securepubads.g.doubleclick.net"};var Ma=function(){return ra("","googleads.g.doubleclick.net")},Na=function(){return ra("","pagead2.googlesyndication.com")},Oa=function(a){return a?"pagead2.googlesyndication.com":ra("","pagead2.googlesyndication.com")};var Ua=function(a,b){if(b)return a.replace(Pa,"&amp;").replace(Qa,"&lt;").replace(Ra,"&gt;").replace(Sa,"&quot;");if(!Ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Pa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Qa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ra,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Sa,"&quot;"));return a},Pa=/&/g,Qa=/</g,Ra=/>/g,Sa=/\"/g,Ta=/[&<>\"]/,Wa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(Va,function(a,
e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var h=Number("0"+e.substr(1));isNaN(h)||(f=String.fromCharCode(h))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},Va=/&([^;\s<&]+);?/g,Xa=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Ya={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},Za={"'":"\\'"},ab=
function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=Ya[d]||(31<e&&127>e?d:$a(d))}b.push('"');return b.join("")},$a=function(a){if(a in Za)return Za[a];if(a in Ya)return Za[a]=Ya[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return Za[a]=b},bb=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,
"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",m=e[h]||"",l=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var r=l.exec(k)||["","",""],G=q.exec(m)||["","",""];if(0==r[0].length&&0==G[0].length)break;var c=0==r[1].length?0:parseInt(r[1],10),Y=0==G[1].length?0:parseInt(G[1],10),c=(c<Y?-1:c>Y?1:0)||((0==r[2].length)<(0==G[2].length)?-1:(0==r[2].length)>(0==G[2].length)?1:0)||(r[2]<G[2]?-1:r[2]>G[2]?
1:0)}while(0==c)}return c};var x=function(a,b){this.width=a;this.height=b};x.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};x.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};x.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};x.prototype.scale=function(a,b){var c=ga(b)?b:a;this.width*=a;this.height*=c;return this};var y=document,z=window,cb=function(a){var b=j;if((a=a.getElementsByTagName("script"))&&a.length)b=a[a.length-1],b=b.parentNode;return b},db=cb(y);Oa();var A=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(j,a[c],c,a)},eb=function(a){return!!a&&"function"==typeof a&&!!a.call},fb=function(a){return!!a&&("object"==typeof a||"function"==typeof a)},gb=function(a,b){if(!a)return n;var c=i;A(b,function(b,e){if(!c||!(e in a)||typeof b!=typeof a[e])c=n});return c},hb=function(a,b){if(2>arguments.length)return a.length;for(var c=1,d=arguments.length;c<d;++c)a.push(arguments[c]);return a.length};
function B(a){return"function"==typeof encodeURIComponent?encodeURIComponent(a):escape(a)}function ib(a,b,c,d){d=d||document;var e=d.createElement("script");e.type="text/javascript";b&&(e.onreadystatechange!==g?e.onreadystatechange=function(){if("complete"==e.readyState||"loaded"==e.readyState)try{b()}catch(a){}}:e.onload=b);c&&(e.id=c);e.src=a;var f=d.getElementsByTagName("head")[0];if(!f)return n;window.setTimeout(function(){f.appendChild(e)},0);return i}
var kb=function(a,b,c,d){return a.addEventListener?(a.addEventListener(b,c,d||n),i):a.attachEvent?(a.attachEvent("on"+b,c),i):n},lb=function(a,b,c){return a.removeEventListener?(a.removeEventListener(b,c,n),i):a.detachEvent?(a.detachEvent("on"+b,c),i):n},mb=function(a){"google_onload_fired"in a||(a.google_onload_fired=n,kb(a,"load",function(){a.google_onload_fired=i}))},nb=function(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=a.document.createElement("img");c.src=b;a.google_image_requests.push(c)},
ob={};function pb(){return("msie"in ob?ob.msie:ob.msie=-1!=navigator.userAgent.toLowerCase().indexOf("msie"))&&!window.opera}
function qb(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE")){for(var a=3,b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(c){b=j}return a.toString()}if(pb()){b=j;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),
a=6,b.AllowScriptAccess="always"}catch(e){if(6==a)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b)return a=b.GetVariable("$version").split(" ")[1],a.replace(/,/g,".")}}return"0"}function rb(a){var b=a.google_ad_format;return b?0<b.indexOf("_0ads"):"html"!=a.google_ad_output&&0<a.google_num_radlinks}function C(a){return!!a&&-1!=a.indexOf("_sdo")}
var sb=function(a,b){if(!(1E-4>Math.random())){var c=Math.random();if(c<b)return c=Math.floor(c/b*a.length),a[c]}return j},tb=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();window.screen&&(a.u_h=window.screen.height,a.u_w=window.screen.width,a.u_ah=window.screen.availHeight,a.u_aw=window.screen.availWidth,a.u_cd=window.screen.colorDepth);navigator.plugins&&(a.u_nplug=navigator.plugins.length);navigator.mimeTypes&&(a.u_nmime=navigator.mimeTypes.length)},
ub=function(a,b){var c=a.length;if(0==c)return 0;for(var d=b||305419896,e=0;e<c;e++)var f=a.charCodeAt(e),d=d^(d<<5)+(d>>2)+f&4294967295;return 0<d?d:4294967296+d},vb=function(a){if(!a)return"";for(var b=[],c=0;a&&25>c;a=a.parentNode,++c)b.push(9!=a.nodeType&&a.id||"");return b.join()},wb=function(a){var b=[z.google_ad_slot,z.google_ad_format,z.google_ad_type,z.google_ad_width,z.google_ad_height];a&&(a=vb(a))&&b.push(a);a=0;b&&(a=ub(b.join(":")));return a.toString()},xb=function(a){try{return!!a.location.href||
""===a.location.href}catch(b){return n}};var yb=function(a,b,c,d){b="border:none;height:"+c+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+b+"px";a=['<ins style="display:inline-table;',b,'">','<ins id="',a,'" style="display:block;',b,'">',d,"</ins></ins>"];return a.join("")};var zb=function(a,b){for(var c=0,d=a,e=0;a!=a.parent;)if(a=a.parent,e++,xb(a))d=a,c=e;else if(b)break;return{win:d,level:c}},Ab=function(a){a=zb(a,i);return a.win},Bb=function(a){a=zb(a,n);return a.win},Cb=j,Db=function(){Cb||(Cb=Ab(window));return Cb};var D=function(a){this.C=[];this.f=a||window;this.e=0;this.B=j},Eb=function(a,b){this.fn=a;this.win=b};D.prototype.enqueue=function(a,b){0==this.e&&0==this.C.length&&(!b||b==window)?(this.e=2,this.da(new Eb(a,window))):this.t(a,b)};D.prototype.t=function(a,b){this.C.push(new Eb(a,b||this.f));this.F()};D.prototype.$=function(a){this.e=1;a&&(this.B=this.f.setTimeout(u(this.D,this),a))};D.prototype.D=function(){1==this.e&&(this.B!=j&&(this.f.clearTimeout(this.B),this.B=j),this.e=0);this.F()};
D.prototype.statusz=function(){return i};na(D.prototype,"nq",D.prototype.enqueue);na(D.prototype,"nqa",D.prototype.t);na(D.prototype,"al",D.prototype.$);na(D.prototype,"rl",D.prototype.D);na(D.prototype,"sz",D.prototype.statusz);D.prototype.F=function(){this.f.setTimeout(u(this.Ga,this),0)};D.prototype.Ga=function(){if(0==this.e&&this.C.length){var a=this.C.shift();this.e=2;a.win.setTimeout(u(this.da,this,a),0);this.F()}};D.prototype.da=function(a){this.e=0;a.fn()};
var Fb=function(a){try{return a.sz()}catch(b){return n}},Gb=function(){var a=Db().google_jobrunner;fb(a)&&(Fb(a)&&eb(a.nq)&&eb(a.nqa)&&eb(a.al)&&eb(a.rl))&&a.rl()};var E=!!window.google_async_iframe_id,Hb=E&&window.parent||window,F=function(){if(E&&!xb(Hb)){for(var a="."+y.domain;2<a.split(".").length&&!xb(Hb);)y.domain=a=a.substr(a.indexOf(".")+1),Hb=window.parent;xb(Hb)||(Hb=window)}return Hb},Ib=function(a){E&&a!=a.parent&&(Gb(),a.google_async_iframe_close&&a.setTimeout(function(){a.document.close()},0))},Jb=function(){if(!E)return db;var a=window.google_async_iframe_id;if(a){for(var a=F().document.getElementById(a),b=0;a&&3>b;++b)a=a.parentNode;return a}return j};var Kb=Array.prototype,Lb=Kb.indexOf?function(a,b,c){return Kb.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(t(a))return!t(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Mb=Kb.forEach?function(a,b,c){Kb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Nb=function(a,b){var c=Lb(a,b),d;(d=0<=c)&&Kb.splice.call(a,c,1);return d},Ob=function(a){var b=a.length;
if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Pb=function(a,b,c){return 2>=arguments.length?Kb.slice.call(a,b):Kb.slice.call(a,b,c)};var H=function(a){this.defaultBucket=[];this.layers={};for(var b=0,c=arguments.length;b<c;++b)this.layers[arguments[b]]=""},Qb=function(a){for(var b=new H,c=0,d=a.defaultBucket.length;c<d;++c)b.defaultBucket.push(a.defaultBucket[c]);A(a.layers,u(H.prototype.M,b));return b};H.prototype.statusz=function(){return i};H.prototype.M=function(a,b){this.layers[b]=a};H.prototype.Da=function(a,b){return""==a?"":!b?(this.defaultBucket.push(a),a):this.layers.hasOwnProperty(b)?this.layers[b]=a:""};
H.prototype.a=function(a,b,c){return this.ta(c)&&!(1E-4>Math.random())&&Math.random()<b?(b=Math.floor(Math.random()*a.length),this.Da(a[b],c)):""};H.prototype.ta=function(a){return!a?i:this.layers.hasOwnProperty(a)&&""==this.layers[a]};H.prototype.b=function(a){return this.layers.hasOwnProperty(a)?this.layers[a]:""};H.prototype.geil=H.prototype.b;
H.prototype.oa=function(){var a=[],b=function(b){""!=b&&a.push(b)};A(this.layers,b);return 0<this.defaultBucket.length&&0<a.length?this.defaultBucket.join(",")+","+a.join(","):this.defaultBucket.join(",")+a.join(",")};var Sb=function(a){this.S=a;Rb(this)},Tb={google_persistent_state:i,google_persistent_state_async:i},Ub={},Vb=function(a){a=a&&Tb[a]?a:E?"google_persistent_state_async":"google_persistent_state";if(Ub[a])return Ub[a];if("google_persistent_state_async"==a)var b=F(),c={};else c=b=F();var d=b[a];return"object"!=typeof d||"object"!=typeof d.S?b[a]=Ub[a]=new Sb(c):Ub[a]=d},Rb=function(a){I(a,3,j);I(a,4,0);I(a,5,0);I(a,6,0);I(a,7,(new Date).getTime());I(a,8,{});I(a,9,{});I(a,10,{});I(a,11,[]);I(a,12,0);
I(a,14,{})},Wb=function(a){switch(a){case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";case 12:return"google_num_slot_to_show";case 14:return"gaGlobal"}},J=function(a,b){var c=Wb(b);return c=
a.S[c]},Xb=function(a,b,c){return a.S[Wb(b)]=c},I=function(a,b,c){a=a.S;b=Wb(b);return a[b]===g?a[b]=c:a[b]},Yb=function(a,b){return Xb(a,3,b)};var Zb,$b,ac=function(a){try{return a.statusz()}catch(b){return n}},K=function(){if(Zb&&ac(Zb))return Zb;var a=Vb(),b=J(a,3);return!b||!fb(b)||!gb(b,H.prototype)||!ac(b)?Zb=Yb(a,new H(1,2,3,4,5,6,7,9,10,11,12)):Zb=b},bc=function(){$b||($b=Qb(K()));return $b},cc={CONTROL:"86748120",EXPERIMENT_BADGE_AFTER_TITLE:"86748121",EXPERIMENT_BADGE_AFTER_TEXT:"86748122",EXPERIMENT_BADGE_BENEATH_CREATIVE:"86748123"},dc={CONTROL:"86726840",EXPERIMENT_BADGE_AFTER_TITLE:"86726841",EXPERIMENT_BADGE_BENEATH_CREATIVE:"86726842"},
ec={CONTROL:"317150300",EXPERIMENT:"317150301"},fc={CONTROL:"33895170",EXPERIMENT:"33895171"},gc={CONTROL:"33895192",CONTROL_NO_FRAME:"33895193",SERIAL:"33895194",SERIAL_W_CACHE_FILL:"33895195",PARALLEL_LONG_TIMEOUT:"33895196",PARALLEL_SHORT_TIMEOUT:"33895197"};var hc={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function ic(a){if(Ja)return n;a=a.google_page_location||a.google_page_url;if(!a)return n;a=a.toString();0==a.indexOf("http://")?a=a.substring(7,a.length):0==a.indexOf("https://")&&(a=a.substring(8,a.length));var b=a.indexOf("/");-1==b&&(b=a.length);a=a.substring(0,b);a=a.split(".");b=n;3<=a.length&&(b=a[a.length-3]in hc);2<=a.length&&(b=b||a[a.length-2]in hc);return b}
var jc=function(a){var b=K();return"44901228"==b.b(1)?n:"44901229"==b.b(1)||Math.random()<ta?1==Math.floor(a/2)%2:n};var L=function(a,b,c){c||(c=Ka?"https":"http");return[c,"://",a,b].join("")};var M=function(a,b){this.x=a!==g?a:0;this.y=b!==g?b:0},kc=function(a,b){return new M(a.x+b.x,a.y+b.y)};M.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};M.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};M.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};M.prototype.translate=function(a,b){a instanceof M?(this.x+=a.x,this.y+=a.y):(this.x+=a,ga(b)&&(this.y+=b));return this};
M.prototype.scale=function(a,b){var c=ga(b)?b:a;this.x*=a;this.y*=c;return this};var lc=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},mc="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),nc=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<mc.length;f++)c=mc[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var oc,pc,rc,sc,tc,uc=function(){return p.navigator?p.navigator.userAgent:j},vc=function(){sc=rc=pc=oc=n;var a;if(a=uc()){var b=p.navigator;oc=0==a.indexOf("Opera");pc=!oc&&-1!=a.indexOf("MSIE");rc=!oc&&-1!=a.indexOf("WebKit");sc=!oc&&!rc&&"Gecko"==b.product}};vc();var wc=oc,N=pc,O=sc,P=rc,xc=function(){var a=p.navigator;return a&&a.platform||""},yc=xc(),zc=function(){tc=-1!=yc.indexOf("Mac")};zc();
var Ac=tc,Cc=function(){var a="",b;wc&&p.opera?(a=p.opera.version,a="function"==typeof a?a():a):(O?b=/rv\:([^\);]+)(\)|;)/:N?b=/MSIE\s+([^\);]+)(\)|;)/:P&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(uc()))?a[1]:""));return N&&(b=Bc(),b>parseFloat(a))?String(b):a},Bc=function(){var a=p.document;return a?a.documentMode:g},Dc=Cc(),Ec={},Q=function(a){return Ec[a]||(Ec[a]=0<=bb(Dc,a))},Fc=function(){var a=p.document;if(a&&N){var b=Bc();return b||("CSS1Compat"==a.compatMode?parseInt(Dc,10):5)}}();var Gc,Hc=!N||N&&9<=Fc;!O&&!N||N&&N&&9<=Fc||O&&Q("1.9.1");N&&Q("9");var Ic=function(a,b){a.className=b},Jc=function(a){a=a.className;return t(a)&&a.match(/\S+/g)||[]},Lc=function(a,b){var c=Jc(a),d=Pb(arguments,1),e=c.length+d.length;Kc(c,d);Ic(a,c.join(" "));return c.length==e},Kc=function(a,b){for(var c=0;c<b.length;c++)0<=Lb(a,b[c])||a.push(b[c])};var Mc=function(a){return a?new R(S(a)):Gc||(Gc=new R)},Nc=function(a){return t(a)?document.getElementById(a):a},Oc=Nc,Qc=function(a,b){lc(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Pc?a.setAttribute(Pc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},Pc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",
type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Rc=function(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new x(a.clientWidth,a.clientHeight)},Sc=function(a){var b=!P&&"CSS1Compat"==a.compatMode?a.documentElement:a.body;a=a.parentWindow||a.defaultView;return new M(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},Uc=function(a,b,c){return Tc(document,arguments)},Tc=function(a,b){var c=b[0],d=b[1];if(!Hc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',
Ua(d.name),'"');if(d.type){c.push(' type="',Ua(d.type),'"');var e={};nc(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(t(d)?c.className=d:s(d)?Lc.apply(j,[c].concat(d)):Qc(c,d));2<b.length&&Vc(a,c,b,2);return c},Vc=function(a,b,c,d){function e(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];fa(f)&&!(ha(f)&&0<f.nodeType)?Mb(Wc(f)?Ob(f):f,e):e(f)}},Xc=function(a){if(1!=a.nodeType)return n;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return n}return i},
Yc=function(a,b){a.appendChild(b)},Zc=function(a,b){Vc(S(a),a,arguments,1)},$c=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):j},ad=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},S=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},Wc=function(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==
typeof a.item||"string"==typeof a.item;if("function"==ea(a))return"function"==typeof a.item}return n},R=function(a){this.s=a||p.document||document};R.prototype.createElement=function(a){return this.s.createElement(a)};R.prototype.createTextNode=function(a){return this.s.createTextNode(String(a))};R.prototype.sa=function(){return"CSS1Compat"==this.s.compatMode};R.prototype.N=function(){return Sc(this.s)};R.prototype.appendChild=Yc;R.prototype.append=Zc;R.prototype.canHaveChildren=Xc;
R.prototype.removeNode=$c;R.prototype.contains=ad;var bd=function(a,b){var c=b||z;a&&c.top!=c&&(c=c.top);try{return c.document&&!c.document.body?new x(-1,-1):Rc(c||window)}catch(d){return new x(-12245933,-12245933)}},cd=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=i;a=bd(!c,a);b.push(a.width.toString());b.push(a.height.toString());return ub(b.join(""))},dd=function(a,b){if(pb()){var c=function(){"complete"==a.readyState&&b()};kb(a,"readystatechange",c)}else kb(a,"load",b)};var T=function(a,b){this.H=a;this.z=b?b.z:[];this.X=b?b.X:n;this.ka=b?b.ka:"";this.Z=b?b.Z:0;this.L=b?b.L:"";this.g=b?b.g:[]};
T.prototype.za=function(a,b){var c=this.H[b],d=this.z;this.H[b]=function(b){if(b&&0<b.length){var f=1<b.length?b[1].url:j;d.push([a,-1!=b[0].url.indexOf("&")?"document"in p?Wa(b[0].url):b[0].url.replace(/&([^;]+);/g,function(a,b){switch(b){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==b.charAt(0)){var c=Number("0"+b.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return a}}):b[0].url,f])}c(b)}};var ed=L(Oa(n),"/pagead/osd.js");
T.prototype.va=function(){this.X||(mb(F()),ib(ed),this.X=i)};T.prototype.u=function(a,b,c){var d=this.z;if(0<d.length)for(var e=a.document.getElementsByTagName("a"),f=0;f<e.length;f++)for(var h=0;h<d.length;h++)if(0<=e[f].href.indexOf(d[h][1])){var k=e[f].parentNode;if(d[h][2])for(var m=k,l=0;4>l;l++){if(0<=m.innerHTML.indexOf(d[h][2])){k=m;break}m=m.parentNode}m=i;b(k,d[h][0],c||0,m);d.splice(h,1);break}if(0<d.length&&a!=Db())try{this.u(a.parent,b,c)}catch(q){}};
T.prototype.V=function(a,b){b&&this.u(this.H,a,1);for(var c=this.g.length,d=0;d<c;d++){var e=this.g[d];!e.W&&e.o&&(a(e.o,e.ha,e.Aa,e.ga),e.W=i)}};T.prototype.U=function(a){this.u(this.H,a,1);for(var b=this.g.length,c=0;c<b;c++){var d=this.g[c];d.o&&(a(d.o,d.ha,d.Aa),d.W=i)}};T.prototype.setupOse=function(a){if(this.getOseId())return this.getOseId();var b=window.google_enable_ose,c;b===i?c=2:b!==n&&((c=sb([2],za))||(c=sb([3],Aa)));if(!c)return 0;this.Z=c;this.L=String(a||0);return this.getOseId()};
T.prototype.getEid=function(){return""};T.prototype.getOseExpId=function(){return this.ka};T.prototype.getOseId=function(){return this.Z};T.prototype.getCorrelator=function(){return this.L};T.prototype.T=function(){return this.z.length+this.g.length};T.prototype.registerAdBlock=function(a,b,c,d){if("js"==c)this.za(a,"google_ad_request_done");else{var e=new fd(a,b,c,d);this.g.push(e);d&&(a=function(){e.ga=i},dd(d,a))}this.va()};
var gd=function(){var a=F(),b=a.__google_ad_urls;if(!b)return a.__google_ad_urls=new T(a);try{b.getOseId()}catch(c){return a.__google_ad_urls=new T(a,b)}return b},fd=function(a,b,c,d){this.ha=a;this.Aa=b;this.Ta=c;this.o=d;this.W=this.ga=n};v("Goog_AdSense_getAdAdapterInstance",gd);v("Goog_AdSense_OsdAdapter",T);v("Goog_AdSense_OsdAdapter.prototype.numBlocks",T.prototype.T);v("Goog_AdSense_OsdAdapter.prototype.getBlocks",T.prototype.U);v("Goog_AdSense_OsdAdapter.prototype.getNewBlocks",T.prototype.V);
v("Goog_AdSense_OsdAdapter.prototype.getEid",T.prototype.getEid);v("Goog_AdSense_OsdAdapter.prototype.getOseExpId",T.prototype.getOseExpId);v("Goog_AdSense_OsdAdapter.prototype.getOseId",T.prototype.getOseId);v("Goog_AdSense_OsdAdapter.prototype.getCorrelator",T.prototype.getCorrelator);v("Goog_AdSense_OsdAdapter.prototype.setupOse",T.prototype.setupOse);v("Goog_AdSense_OsdAdapter.prototype.registerAdBlock",T.prototype.registerAdBlock);var hd={CONTROL:"X",CONTROL_NO_FRAME:"XN",SERIAL:"S",SERIAL_W_CACHE_FILL:"SC",PARALLEL_LONG_TIMEOUT:"PL",PARALLEL_SHORT_TIMEOUT:"PS"},id=function(a){return"zrt_ads_frame"+a.google_unique_id};var U=function(a,b){this.I=a;this.ma=b;this.ba=n;this.p="";this.J=j;this.aa=this.Ia=n;var c=this;this.handler=function(a){c.pa(a)};kb(a,"message",this.handler)},jd="zrt_ready",kd="zrt_cancel",ld=j,md=function(a,b){ld=new U(a,b)};U.prototype.fa=function(){return this.Ia};U.prototype.K=function(){this.p="";this.aa=i;this.ba&&(this.G(kd),lb(this.I,"message",this.handler))};U.prototype.Ca=function(a,b){this.aa||(this.p=a,this.J=b,this.ba&&this.ea())};
U.prototype.pa=function(a){var b=this.R();this.ma==a.origin&&(b&&b==a.source&&jd==a.data)&&(this.ba=i,lb(this.I,"message",this.handler),this.aa?this.G(kd):this.p&&this.J&&this.ea())};U.prototype.Q=function(){return this.I.document.getElementById(id(this.I))};U.prototype.R=function(){var a=this.Q();return a?a.contentWindow:j};U.prototype.G=function(a){var b=this.R();b&&b.postMessage(a,this.ma)};
U.prototype.ea=function(){var a=this.Q();A(this.J,function(b,c){a.setAttribute(c,b)});a.style.display="";this.G(this.p);this.Ia=i};(function(){var a="^https?://(",b=[];A(La,function(a){b.push(a.replace(/\./g,"\\."))});a+=b.join("|")+")(:\\d{2,5})?/";return RegExp(a,"i")})();var nd=function(){var a="";if(document.documentMode){var b=document.createElement("IFRAME");b.frameBorder=0;b.style.height=0;b.style.width=0;b.style.position="absolute";if(document.body){document.body.appendChild(b);try{var c=b.contentWindow.document;c.open();c.write("<!DOCTYPE html>");c.close();a+=c.documentMode}catch(d){}document.body.removeChild(b)}}return a};var od=function(a){this.f=a;a.google_iframe_oncopy||(a.google_iframe_oncopy={handlers:{}});this.Ma=a.google_iframe_oncopy};Ua("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){w.location.replace(h)}}");od.prototype.set=function(a,b){this.Ma.handlers[a]=b;this.f.addEventListener&&this.f.addEventListener("load",u(this.na,this,a),n)};
od.prototype.na=function(a){a=this.f.document.getElementById(a);var b=a.contentWindow.document;if(a.onload&&b&&(!b.body||!b.body.firstChild))a.onload()};var pd=function(a){a=a.webkitVisibilityState||a.mozVisibilityState||"";var b={visible:1,hidden:2,prerender:3,preview:4};return b[a]||0};var qd=function(a,b){var c=S(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,j))?c[b]||c.getPropertyValue(b)||"":""},V=function(a,b){return qd(a,b)||(a.currentStyle?a.currentStyle[b]:j)||a.style&&a.style[b]},rd=function(a){a=a?S(a):document;return N&&!(N&&9<=Fc)&&!Mc(a).sa()?a.body:a.documentElement},sd=function(a){var b=a.getBoundingClientRect();N&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b},td=function(a){if(N&&!(N&&8<=Fc))return a.offsetParent;var b=S(a),c=V(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=V(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return j},ud=function(a){var b,c=S(a),d=V(a,"position"),e=O&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&
(0>b.screenX||0>b.screenY),f=new M(0,0),h=rd(c);if(a==h)return f;if(a.getBoundingClientRect)b=sd(a),a=Mc(c).N(),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(h),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(P&&"fixed"==V(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(wc||P&&"absolute"==d)f.y-=
c.body.offsetTop;for(b=a;(b=td(b))&&b!=c.body&&b!=h;)if(f.x-=b.scrollLeft,!wc||"TR"!=b.tagName)f.y-=b.scrollTop}return f},wd=function(a,b){var c=new M(0,0),d=S(a)?S(a).parentWindow||S(a).defaultView:window,e=a;do{var f=d==b?ud(e):vd(e);c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c},vd=function(a){var b=new M;if(1==a.nodeType){if(a.getBoundingClientRect){var c=sd(a);b.x=c.left;b.y=c.top}else{var c=Mc(a).N(),d=ud(a);b.x=d.x-c.x;b.y=d.y-c.y}O&&!Q(12)&&(b=kc(b,xd(a)))}else c=
"function"==ea(a.v),d=a,a.targetTouches?d=a.targetTouches[0]:c&&a.v().targetTouches&&(d=a.v().targetTouches[0]),b.x=d.clientX,b.y=d.clientY;return b},yd=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b},zd=function(a){var b=S(a),c="";if(b.body.createTextRange){b=b.body.createTextRange();b.moveToElementText(a);try{c=b.queryCommandValue("FontName")}catch(d){c=
""}}c||(c=V(a,"fontFamily"));a=c.split(",");1<a.length&&(c=a[0]);return Xa(c,"\"'")},Ad=/[^\d]+$/,Bd=function(a){return(a=a.match(Ad))&&a[0]||j},Cd={cm:1,"in":1,mm:1,pc:1,pt:1},Dd={em:1,ex:1},Ed=function(a){var b=V(a,"fontSize"),c=Bd(b);if(b&&"px"==c)return parseInt(b,10);if(N){if(c in Cd)return yd(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&c in Dd)return a=a.parentNode,c=V(a,"fontSize"),yd(a,b==c?"1em":b,"left","pixelLeft")}c=Uc("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});
Yc(a,c);b=c.offsetHeight;$c(c);return b},Fd=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/,xd=function(a){var b;N?b="-ms-transform":P?b="-webkit-transform":wc?b="-o-transform":O&&(b="-moz-transform");var c;b&&(c=V(a,b));c||(c=V(a,"transform"));if(!c)return new M(0,0);a=c.match(Fd);return!a?new M(0,0):new M(parseFloat(a[1]),parseFloat(a[2]))};var Gd={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_sc_id:"sc_id",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Hd={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",
google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_loeid:"loeid",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_mtl:"mtl",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_sui:"sui",google_skip:"skip",google_tdsma:"tdsma",google_tfs:"tfs",google_tl:"tl"},Id={google_lact:"lact",google_only_pyv_ads:"pyv",google_only_userchoice_ads:"uc",google_scs:"scs",google_with_pyv_ads:"withpyv",google_previous_watch:"p_w",google_previous_searches:"p_s",google_yt_pt:"yt_pt",google_yt_up:"yt_up"};var Jd=function(a){var b=2;try{a.top.document==a.document?b=0:xb(a.top)&&(b=1)}catch(c){}return b};function Kd(a,b){try{return a.top.document==b}catch(c){}return n}function Ld(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(Kd(a,b))return n;var e=b.documentElement;if(c&&d){var f=1,h=1;a.innerHeight?(f=a.innerWidth,h=a.innerHeight):e&&e.clientHeight?(f=e.clientWidth,h=e.clientHeight):b.body&&(f=b.body.clientWidth,h=b.body.clientHeight);if(h>2*d||f>2*c)return n}return i}function Md(a,b){A(b,function(b,d){a["google_"+d]=b})}
var Nd=function(a){var b=F().google_top_url;if(b)return{url:b,isTopUrl:i,isJp:i};b=a.location.href;if(a==a.top)return{url:b,isTopUrl:i,isJp:n};var c=n,d=a.document;d&&d.referrer&&(b=d.referrer,a.parent==a.top&&(c=i));return{url:b,isTopUrl:c,isJp:n}};function Od(a,b,c,d){var e=Jd(F());a=!!a.google_referrer_url;var f=4;!b&&1==e?f=5:!b&&2==e?f=6:b&&1==e?f=7:b&&2==e&&(f=8);f+=5*a;c&&(f|=16);d&&(f|=32);return""+f}function Pd(a,b,c){a.page_url=!c?b.URL:b.referrer;a.page_location=j}
function Qd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=(!d?c.URL:c.referrer)||"EMPTY"}function Rd(a,b){var c={},d=Bb(window),d=Nd(d),e=Ld(F(),b,a.google_ad_width,a.google_ad_height);c.iframing=Od(a,e,d.isTopUrl,d.isJp);a.google_page_url?Qd(c,a,b,e):Pd(c,b,e);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1E3:j;c.referrer_url=e?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}
function Sd(a){for(var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));-1<c.indexOf("%");)try{c=decodeURIComponent(c)}catch(d){break}b.iframing=j;b.page_url=c;b.page_location=a.URL;b.last_modified_time=j;b.referrer_url=c;return b}function Td(a){var b=Ud(a,F().document);Md(a,b)}function Ud(a,b){var c;return c=a.google_page_url==j&&Vd[b.domain]?Sd(b):Rd(a,b)}var Vd={"ad.yieldmanager.com":i};var Wd=function(a,b,c){b=u(b,p,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";d.fileName&&(e=d.fileName);var f=-1;d.lineNumber&&(f=d.lineNumber);b=b(c,e,f);if(!b)throw d;}window.onerror=a};v("google_protectAndRun",Wd);
var Yd=function(a,b,c,d){if(0.01>Math.random()){var e=y;a=["/pagead/gen_204","?id=jserror","&jscb=",Ha?1:0,"&jscd=",Ia?1:0,"&context=",B(a),"&msg=",B(b),"&file=",B(c),"&line=",B(d.toString()),"&url=",B(e.URL.substring(0,512)),"&ref=",B(e.referrer.substring(0,512))];a.push(Xd());a=L(Na(),a.join(""));nb(z,a)}return!Ja};v("google_handleError",Yd);
var $d=function(a){Zd|=a},Zd=0,Xd=function(){var a=["&client=",B(z.google_ad_client),"&format=",B(z.google_ad_format),"&slotname=",B(z.google_ad_slot),"&output=",B(z.google_ad_output),"&ad_type=",B(z.google_ad_type)];return a.join("")};var de=function(){window.google_ad_output==j&&(window.google_ad_output="html");if(C(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);a&&(window.google_ad_width=parseInt(a[1],10),window.google_ad_height=parseInt(a[2],10),window.google_ad_output="html")}window.google_ad_format=ae(window.google_ad_format,String(window.google_ad_output),Number(window.google_ad_width),Number(window.google_ad_height),window.google_ad_slot,!!window.google_override_format);window.google_ad_client=
be(window.google_ad_format,window.google_ad_client);Td(window);window.google_flash_version==j&&(window.google_flash_version=qb());window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();s(window.google_color_bg)&&(window.google_color_bg=ce(window.google_color_bg,a));s(window.google_color_text)&&(window.google_color_text=ce(window.google_color_text,a));s(window.google_color_link)&&(window.google_color_link=
ce(window.google_color_link,a));s(window.google_color_url)&&(window.google_color_url=ce(window.google_color_url,a));s(window.google_color_border)&&(window.google_color_border=ce(window.google_color_border,a));s(window.google_color_line)&&(window.google_color_line=ce(window.google_color_line,a))},ee=function(a){A(Gd,function(b,c){a[c]=j});A(Hd,function(b,c){a[c]=j});A(Id,function(b,c){a[c]=j});a.google_container_id=j;a.google_enable_async=j;a.google_eids=j;a.google_page_location=j;a.google_referrer_url=
j;a.google_show_ads_impl=j;a.google_ad_region=j;a.google_gl=j;a.google_iframe_name=j;a.google_loader_used=j},ce=function(a,b){$d(2);return a[b%a.length]},be=function(a,b){if(!b)return"";b=b.toLowerCase();return b=C(a)?fe(b):ge(b)},ge=function(a){a&&"ca-"!=a.substring(0,3)&&(a="ca-"+a);return a},fe=function(a){a&&"ca-aff-"!=a.substring(0,7)&&(a="ca-aff-"+a);return a},ae=function(a,b,c,d,e,f){!a&&"html"==b&&(a=c+"x"+d);return a=(!a?0:!e||f)?a.toLowerCase():""};var W=navigator;
function he(a,b,c,d,e){var f=Math.round((new Date).getTime()/1E3),h=window.google_analytics_domain_name;a="undefined"==typeof h?ie("auto",a):ie(h,a);var k=-1<b.indexOf("__utma="+a+"."),h=-1<b.indexOf("__utmb="+a),m=-1<b.indexOf("__utmc="+a),l=Vb("google_persistent_state"),l=J(l,14)||Xb(l,14,{});k?(b=b.split("__utma="+a+".")[1].split(";")[0].split("."),h&&m?l.sid=b[3]+"":l.sid||(l.sid=f+""),l.vid=b[0]+"."+b[1],l.from_cookie=i):(l.sid||(l.sid=f+""),l.vid||(l.vid=(Math.round(2147483647*Math.random())^
je(b,c,d,e)&2147483647)+"."+f),l.from_cookie=n);l.dh=a;l.hid||(l.hid=Math.round(2147483647*Math.random()));return l}function je(a,b,c,d){var e=[W.appName,W.version,W.language?W.language:W.browserLanguage,W.platform,W.userAgent,W.javaEnabled()?1:0].join("");c?e+=c.width+"x"+c.height+c.colorDepth:window.java&&(c=java.awt.Toolkit.getDefaultToolkit().getScreenSize(),e+=c.screen.width+"x"+c.screen.height);e+=a;e+=d||"";for(a=e.length;0<b;)e+=b--^a++;return ke(e)}
function ke(a){var b=1,c=0,d;if(!(a==g||""==a)){b=0;for(d=a.length-1;0<=d;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=0!=c?b^c>>21:b}return b}function ie(a,b){if(!a||"none"==a)return 1;a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return ke(a.toLowerCase())};var le=[],me=n,ne=function(a){if(me)for(var b=le,c=0;c<b.length;c++)a(u(b[c].wrap,b[c]))};var oe=function(a){oe[" "](a);return a};oe[" "]=ca;var pe=function(a,b){try{return oe(a[b]),i}catch(c){}return n};var qe=!N||N&&9<=Fc,re=N&&!Q("9");!P||Q("528");O&&Q("1.9b")||N&&Q("8")||wc&&Q("9.5")||P&&Q("528");O&&!Q("8")||N&&Q("9");var se=function(a,b){this.type=a;this.currentTarget=this.target=b};se.prototype.n=n;se.prototype.defaultPrevented=n;se.prototype.Ba=i;se.prototype.stopPropagation=function(){this.n=i};se.prototype.preventDefault=function(){this.defaultPrevented=i;this.Ba=n};var X=function(a,b){a&&this.init(a,b)};oa(X,se);X.prototype.target=j;X.prototype.relatedTarget=j;X.prototype.offsetX=0;X.prototype.offsetY=0;X.prototype.clientX=0;X.prototype.clientY=0;X.prototype.screenX=0;X.prototype.screenY=0;X.prototype.button=0;X.prototype.keyCode=0;X.prototype.charCode=0;X.prototype.ctrlKey=n;X.prototype.altKey=n;X.prototype.shiftKey=n;X.prototype.metaKey=n;X.prototype.ya=n;X.prototype.i=j;
X.prototype.init=function(a,b){var c=this.type=a.type;se.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?O&&(pe(d,"nodeName")||(d=j)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=P||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=P||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;
this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ya=Ac?a.metaKey:a.ctrlKey;this.state=a.state;this.i=a;a.defaultPrevented&&this.preventDefault();delete this.n};X.prototype.stopPropagation=function(){X.Fa.stopPropagation.call(this);this.i.stopPropagation?this.i.stopPropagation():this.i.cancelBubble=i};
X.prototype.preventDefault=function(){X.Fa.preventDefault.call(this);var a=this.i;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,re)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};X.prototype.v=function(){return this.i};var te={},Z={},ue={},ve="on",we={},ye=function(a){if(!te[a])return n;var b=te[a];if(b.removed)return n;var c=b.src,d=b.type,e=b.proxy,f=b.capture;c.removeEventListener?(c==p||!c.Na)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in we?we[d]:we[d]=ve+d,e);c=c[ia]||(c[ia]=++ja);ue[c]&&(e=ue[c],Nb(e,b),0==e.length&&delete ue[c]);b.removed=i;if(b=Z[d][f][c])b.wa=i,xe(d,f,c,b);delete te[a];return i},xe=function(a,b,c,d){if(!d.A&&d.wa){for(var e=0,f=0;e<d.length;e++)if(d[e].removed){var h=
d[e].proxy;h.src=j}else e!=f&&(d[f]=d[e]),f++;d.length=f;d.wa=n;0==f&&(delete Z[a][b][c],Z[a][b].m--,0==Z[a][b].m&&(delete Z[a][b],Z[a].m--),0==Z[a].m&&delete Z[a])}},Ae=function(a,b,c,d,e){var f=1;b=b[ia]||(b[ia]=++ja);if(a[b]){var h=--a.j,k=a[b];k.A?k.A++:k.A=1;try{for(var m=k.length,l=0;l<m;l++){var q=k[l];q&&!q.removed&&(f&=ze(q,e)!==n)}}finally{a.j=Math.max(h,a.j),k.A--,xe(c,d,b,k)}}return Boolean(f)},ze=function(a,b){a.callOnce&&ye(a.key);return a.handleEvent(b)},Ce=function(a,b){if(a.removed)return i;
var c=a.type,d=Z;if(!(c in d))return i;var d=d[c],e,f;if(!qe){e=b||ba("window.event");var h=i in d,k=n in d;if(h){if(0>e.keyCode||e.returnValue!=g)return i;Be(e)}var m=new X;m.init(e,this);e=i;try{if(h){for(var l=[],q=m.currentTarget;q;q=q.parentNode)l.push(q);f=d[i];f.j=f.m;for(var r=l.length-1;!m.n&&0<=r&&f.j;r--)m.currentTarget=l[r],e&=Ae(f,l[r],c,i,m);if(k){f=d[n];f.j=f.m;for(r=0;!m.n&&r<l.length&&f.j;r++)m.currentTarget=l[r],e&=Ae(f,l[r],c,n,m)}}else e=ze(a,m)}finally{l&&(l.length=0)}return e}c=
new X(b,this);return e=ze(a,c)},Be=function(a){var b=n;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=i}if(b||a.returnValue==g)a.returnValue=i};ne(function(a){Ce=a(Ce)});var De=function(){};da(De);De.getInstance();var Ee=function(){this.r=[]};Ee.prototype.d=function(a,b,c){this.r.push(new Fe(a,b,c))};Ee.prototype.q=function(a){this.d(a,"zIndex",999999)};Ee.prototype.Ha=function(){for(var a=this.r.length-1;0<=a;a--)this.r[a].undo();this.r.length=0};var Fe=function(a,b,c){this.xa=a;this.Ka=b;this.La=a.style[b];this.xa.style[b]=c};Fe.prototype.undo=function(){this.xa.style[this.Ka]=this.La};var $=function(a,b,c,d,e,f){this.ua=n;this.Ja=a;this.ca=e;this.ia=f;this.Ua=b;this.l=+c;this.k=+d;this.c=new Ee;this.Y=j;this.Sa=this.l;this.Qa=this.k;this.Pa=this.Ra=j};$.prototype.collapse=function(){var a=this.P();a&&(this.Y&&(this.Y.cleanup(),this.Y=j),this.c.Ha(),this.Oa=this.ua=n)};$.prototype.la=function(a,b,c){this.c.d(a,"width",b+"px");this.c.d(a,"height",c+"px");this.c.q(a)};
$.prototype.O=function(){var a=[],b=this.P();if(!b)return a;a.push(b);this.ca&&this.ia&&a.push(this.ca.document.getElementById(this.ia));return a};$.prototype.expand=function(a,b,c){var d=this.O();if(!(0>=d.length)){for(var e=0,f=d.length;e<f;++e)this.la(d[e],a,b);d=d[d.length-1];a>this.l&&(0==c||3==c)&&this.c.d(d,"left","-"+(a-this.l)+"px");b>this.k&&(1==c||0==c)&&this.c.d(d,"top","-"+(b-this.k)+"px");this.Ea(d,n);this.ua=i}};
$.prototype.Ea=function(a,b){var c=a.parentNode,d=c.parentNode;"ins"==c.nodeName.toLowerCase()&&!b&&(this.c.q(c),this.c.q(d));for(c=d.parentNode;c&&c.style&&"body"!=c.nodeName.toLowerCase();c=c.parentNode)if("visible"!=c.style.overflow&&this.c.d(c,"overflow","visible"),b){var d=c,e=V(d,"position"),f=V(d,"zIndex");"static"!=e&&"auto"!=f&&this.c.d(d,"zIndex","auto")}};
$.prototype.ja=function(a,b){var c=this.O(),c=c[c.length-1],c=vd(c),d=this.ca||z,d=Rc(d||window),e=a-this.l,f=b-this.k,h=c.y,f=f>h,k=d.height-(c.y+this.k),h=f||k>=h,f=c.x,e=e>f,c=d.width-(c.x+this.l),c=e||c>=f,d=2;h&&!c?d=3:!h&&c?d=1:!h&&!c&&(d=0);return d};$.prototype.P=function(){this.qa||(this.qa=y.getElementById(this.Ja));return this.qa};var Ge=function(a,b){var c=a.ja(b.width,b.height);a.expand(b.width,b.height,c);return{width:b.width,height:b.height,direction:c}},He=function(a){a.collapse();return{}},Ie=function(a,b){var c={},d=new $(b.id,"",b.width,b.height,b.topMostFriendlyWindow,b.friendlyIframeId);c.expand=ma(Ge,d);c.collapse=ma(He,d);d={};iframes.open(a,b,d,c)},Je=function(){iframes.setHandler("expandable",{onOpen:function(a){var b=a.getOpenParams(),c=b.container,d=b.width,e=b.height,f=b.id,h=f+"_anchor";if(b.friendlyIframeId)c=
document.createElement("div"),document.body.appendChild(c);else{var k=yb(h,d,e,"");c?(c.innerHTML=k,c=c.firstChild.firstChild):(document.write(k),c=document.getElementById(h))}return a=a.openInto(c,{id:f,width:d,height:e,style:b.cssStyle})},onReady:function(){},onClose:function(){}})};var Ke=(new Date).getTime();var Le=function(a){var b="google_unique_id";a[b]?++a[b]:a[b]=1;return a[b]},Me=function(a){var b="google_unique_id";a=a[b];return"number"==typeof a?a:0},Oe=function(a,b){try{if(a.google_allow_expandable_ads===n||!b.body||a.google_ad_output&&"html"!=a.google_ad_output||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||b.domain!=a.location.hostname||!Ne(navigator,b))return i}catch(c){return i}return n},Ne=function(a,b){var c=a.userAgent,d=a.platform;if(/Win|Mac|Linux/.test(d)&&!/^Opera/.test(c)){var e=
(/WebKit\/(\d+)/.exec(c)||[0,0])[1],f=(/rv\:(\d+\.\d+)/.exec(c)||[0,0])[1];if(/Win/.test(d)&&/MSIE.*Trident/.test(c)&&7<b.documentMode||!e&&"Gecko"==a.product&&1.7<f&&!/rv\:1\.8([^.]|\.0)/.test(c)||524<e)return i}return n},Pe=function(){return"object"==typeof window.ExpandableAdSlotFactory&&"function"==typeof window.ExpandableAdSlotFactory.createIframe},Qe=function(a){var b=["<iframe"];A(a,function(a,d){b.push(" "+d+'="'+(a==j?"":a)+'"')});b.push("></iframe>");return b.join("")},Re=function(a,b,c){c.id=
b;c.name=b;c.src=L(Ma(),["/pagead/html/",Fa(),"/r20121214/zrt_lookup.html",a?"#"+a:""].join(""));return Qe(c)},Te=function(){var a=Se,b=ec;if(window.google_top_experiment){var c;switch(window.google_top_experiment){case a.EXPERIMENT:c=b.EXPERIMENT;break;case a.CONTROL:c=b.CONTROL}c&&K().a([c],1,10)}},Ue=function(){var a=fc;window.google_expand_experiment&&(a="expt"==window.google_expand_experiment?a.EXPERIMENT:"control"==window.google_expand_experiment?
a.CONTROL:j)&&K().a([a],1,5)},Ve=function(){window.google_top_experiment&&Te();window.google_expand_experiment&&Ue()},We=function(a,b){var c=b.cli.toLowerCase();c&&!/^ca-/.test(c)&&(c="ca-"+c);return[a,b.w,b.h,b.adk,b.type,b.slot,b.fmt,c==window.google_ad_client?"":c].join(".")},Xe=function(a){a=a.google_async_slots;var b=String(Me(window)),c=a[b];c&&c.sent&&(b+="b",c=a[b]);if(!c||c.sent)return{pasl:"",fasl:""};var d=[];A(a,function(a,c){c!=b&&!a.sent&&(d.push(We(c,a)),a.saw.push(b))});c.sent=i;return{pasl:c.saw.join(",").slice(0,
20),fasl:d.join("|").slice(0,100)}},Se={EXPERIMENT:"jp_e",CONTROL:"jp_c"};var Ye=Oa(n),Ze=20,$e=500,af={};function bf(a,b){a&&""!=a&&(af[b]=1==b?af[b]?af[b]+(","+a):a:a)}function cf(){var a=[];A(af,function(b){a.push(b)});return a.join(",")}function df(a,b){if(s(a))for(var c=0;c<a.length;c++)t(a[c])&&bf(a[c],b)}var ef=n;
function ff(a,b,c){var d="script";if(E?1==Me(a):!Me(a))K().a(["30143102","30143103"],xa,5),K().a(["33895251"],ya,7);ef=gf(a,b);ef||(a.google_allow_expandable_ads=n);var e=!Pe(),f=cc;if(ef&&e){K().a(["30143205","30143206"],0,5);"undefined"!=typeof window.iframes&&$d(8);K().a(["33895220","33895222","33895224","33895225"],ua,5);var h=[f.CONTROL,f.EXPERIMENT_BADGE_AFTER_TITLE,f.EXPERIMENT_BADGE_AFTER_TEXT,f.EXPERIMENT_BADGE_BENEATH_CREATIVE];K().a(h,va,5);var h=dc,k=[h.CONTROL,h.EXPERIMENT_BADGE_AFTER_TITLE,
h.EXPERIMENT_BADGE_BENEATH_CREATIVE];K().a(k,wa,5);k=K().b(5);"33895222"==k||"33895224"==k||"33895225"==k||k==f.CONTROL||k==f.EXPERIMENT_BADGE_AFTER_TITLE||k==f.EXPERIMENT_BADGE_AFTER_TEXT||k==f.EXPERIMENT_BADGE_BENEATH_CREATIVE||k==h.CONTROL||k==h.EXPERIMENT_BADGE_AFTER_TITLE||k==h.EXPERIMENT_BADGE_BENEATH_CREATIVE?b.write("<"+d+' src="https://web.archive.org/web/20130130204307/https://ssl.gstatic.com/gb/js/gcm_01fa0dcbd17f41ae40e2e164313785ce.js"></'+d+">"):"33895223"==k?b.write("<"+d+' src="'+L(Ye,"/pagead/js/gcm_01fa0dcbd17f41ae40e2e164313785ce.js")+'"></'+d+">"):"33895221"==
k?b.write("<"+d+' src="'+L(Ye,"/pagead/js/expansion_embed_exp.js")+'"></'+d+">"):b.write("<"+d+' src="'+L(Ye,"/pagead/expansion_embed.js")+'"></'+d+">");("33895224"==k||"33895225"==k)&&b.write("<"+d+' src="'+L(Ye,"/pagead/expansion_embed.js")+'"></'+d+">")}c=e||c;if("PL"==a.google_ad_handling_experiment||"PS"==a.google_ad_handling_experiment)e=L(Ma(),""),md(a,e);c&&pb()?b.write("<"+d+' src="'+L(Ye,"/pagead/render_ads.js")+'"></'+d+">"):b.write("<"+d+'>google_protectAndRun("ads_core.google_render_ad", google_handleError, google_render_ad);</'+
d+">")}function hf(a){return a!=j?'"'+a+'"':'""'}var jf=function(a,b){if("about:blank"===b)return b;var c=b.slice(-1),d="?"==c||"#"==c?"":"&",e=[b],c=function(a,b){if(a||0===a||a===n)"boolean"==typeof a&&(a=a?1:0),hb(e,d,b,"=",B(a)),d="&"};A(a,c);return e.join("")};function gf(a,b){var c=a.google_ad_width,d=a.google_ad_height,e=F();return Oe(a,b)||Ld(e,e.document,c,d)||!kf(a)?n:i}function kf(a){a=a.google_ad_format;return C(a)?n:i}var lf=function(){var a=gd(),b=Vb();return a.setupOse(J(b,7))};
function mf(a,b,c,d){E||Le(a);var e=Me(a);c=jf({ifi:e},c);c=c.substring(0,1991);c=c.replace(/%\w?$/,"");var f="script",h="google_ads_frame"+e,k=K().b(5),m=bc().b(4),l=j,q={id:h,name:h,width:String(a.google_ad_width),height:String(a.google_ad_height),frameborder:"0",src:"",marginwidth:"0",marginheight:"0",vspace:"0",hspace:"0",allowtransparency:"true",scrolling:"no"};if(("js"==a.google_ad_output||"json_html"==a.google_ad_output)&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+
f+' language="JavaScript1.1" src='+hf(nf(c))+"></"+f+">");else if("html"==a.google_ad_output){var r=ef?c.replace(/&ea=[^&]*/,"")+"&ea=0":c;q.src=nf(r);var G=Qe(q),Y=cc,jb=dc,f=gc;d=a.google_container_id||d||j;if("object"==typeof iframes&&"function"==typeof iframes.open&&("33895222"==k||"33895223"==k||"33895225"==k||k==Y.CONTROL||k==Y.EXPERIMENT_BADGE_AFTER_TITLE||k==Y.EXPERIMENT_BADGE_AFTER_TEXT||k==Y.EXPERIMENT_BADGE_BENEATH_CREATIVE||k==jb.CONTROL||k==jb.EXPERIMENT_BADGE_AFTER_TITLE||k==jb.EXPERIMENT_BADGE_BENEATH_CREATIVE))Je(),
iframes.setVersionOverride("gcm_01fa0dcbd17f41ae40e2e164313785ce.js"),m={style:"expandable",id:h,rpcToken:"adsense_rpc_key",width:a.google_ad_width,height:a.google_ad_height,cssStyle:"left:0;position:absolute;top:0",topMostFriendlyWindow:F(),friendlyIframeId:a.google_async_iframe_id},Ie(nf(c),m);else if((m==f.SERIAL||m==f.SERIAL_W_CACHE_FILL)&&E)m=Re("U="+nf(r),id(a),q),b.write(m);else if((m==f.PARALLEL_LONG_TIMEOUT||m==f.PARALLEL_SHORT_TIMEOUT)&&E){var Ga=ld;delete q.id;delete q.name;delete q.src;Ga.Ca(nf(r),
q);Ga.fa()||(q=function(){Ga.fa()||(Ga.K(),b.write(G))},a.setTimeout(q,m==f.PARALLEL_SHORT_TIMEOUT?Ze:$e))}else ef&&Pe()?a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe(h,nf(c),a.google_ad_width,a.google_ad_height,d,F(),a.google_async_iframe_id):a.google_container_id?of(a.google_container_id,b,G):b.write(G);l=document.getElementById(h);E&&pf(a.google_async_iframe_id,G);if(qf){if(3!=pd(b))rf("/pagead/ads?",l);else{var qc=function(){rf("/pagead/ads?",l);lb(y,"webkitvisibilitychange",
qc)};kb(b,"webkitvisibilitychange",qc)}qf=n}}"30143103"==k&&(1==e&&!a.google_container_id)&&b.write('<iframe height=1 src="'+L(Ye,"/pagead/s/iframes_api_loader.html")+'" style="position:absolute;visibility:hidden" width=1></iframe>');a=gd();a.getOseId()&&a.registerAdBlock(c,1,String(window.google_ad_output||""),l);return c}var pf=function(a,b){var c="javascript:"+ab(["<!DOCTYPE html><html><body>",b,"</body></html>"].join("")),d=F();(new od(d)).set(a,c)};function sf(a){ee(a)}
var vf=function(a,b){var c="44901217"==bc().b(2);if(!tf(c))return n;var d=!ic(window)?jc(Me(window))?ra("","googleads2.g.doubleclick.net"):Ma():Na(),c=uf(a);if(C(window.google_ad_format))return window.google_ad_url="about:blank",i;d=L(d,b+"");window.google_ad_url=jf(c,d);return i},qf=n,wf=function(a){var b=K().b(9);return"html"===z.google_ad_output&&3==pd(y)&&"373855200"===b?(qf=i,$d(32),vf(a,"/pagead/gen_204?id=prerender")):vf(a,"/pagead/ads?")},zf=
function(a){a.dt=Ke;E&&window.google_bpp&&(a.bpp=window.google_bpp);a.shv=Fa();var b=!!window.google_test_1,c=!!window.google_test_2;b&&(a.tsi=c?"3":"2");a.jsv="/r20121214".replace("/","");window.google_loader_used&&(a.saldr=1);var b=Vb(),c=J(b,8),d=window.google_ad_section,e=window.google_ad_format,f=window.google_ad_slot;c[d]&&(C(e)||(a.prev_fmts=c[d]));var h=J(b,9);h[d]&&(a.prev_slotnames=h[d].toLowerCase());e?C(e)||(c[d]=c[d]?c[d]+
(","+e):e):f&&(h[d]=h[d]?h[d]+(","+f):f);a.correlator=J(b,7);if(window.google_ad_channel){c=J(b,10);d="";e=window.google_ad_channel.split(xf);for(f=0;f<e.length;f++)h=e[f],c[h]?d+=h+"+":c[h]=i;a.pv_ch=d}window.google_ad_host_channel&&(b=yf(window.google_ad_host_channel,J(b,11)),a.pv_h_ch=b);Ha&&(a.jscb=1);Ia&&(a.jscd=1);a.frm=window.google_iframing;a.adk=E&&window.google_ad_unit_key?String(window.google_ad_unit_key):wb(Jb());b=F().document;b=he(b.domain,b.cookie,window.history.length,window.screen,
b.referrer);a.ga_vid=b.vid;a.ga_sid=b.sid;a.ga_hid=b.hid;a.ga_fc=b.from_cookie;a.ga_wpids=window.google_analytics_uacct},Af=function(a){var b=F(),c=n,d=bd(c,b.top);d&&(a.biw=d.width,a.bih=d.height);if(b.top!=b&&(b=bd(c,b)))a.isw=b.width,a.ish=b.height},Bf=function(a){var b=cd(F());0!=b&&(a.ifk=b.toString())},Cf=function(a){var b=gd();(b=b.getOseId())&&(a.oid=b)};
function yf(a,b){for(var c=a.split("|"),d=-1,e=[],f=0;f<c.length;f++){var h=c[f].split(xf);b[f]||(b[f]={});for(var k="",m=0;m<h.length;m++){var l=h[m];""!=l&&(b[f][l]?k+="+"+l:b[f][l]=i)}k=k.slice(1);e[f]=k;""!=k&&(d=f)}c="";if(-1<d){for(f=0;f<d;f++)c+=e[f]+"|";c+=e[d]}return c}function Df(){var a=["44901228","44901229"];K().a(a,sa,1);a=["44901218","44901217"];K().a(a,Ba,2);"html"===z.google_ad_output&&3==pd(y)&&(a=["373855201","373855200"],K().a(a,Ca,9))}
var Ef=function(a){var b=hd,c=gc,d;switch(a){case b.CONTROL:d=c.CONTROL;break;case b.CONTROL_NO_FRAME:d=c.CONTROL_NO_FRAME;break;case b.SERIAL:d=c.SERIAL;break;case b.SERIAL_W_CACHE_FILL:d=c.SERIAL_W_CACHE_FILL;break;case b.PARALLEL_LONG_TIMEOUT:d=c.PARALLEL_LONG_TIMEOUT;break;case b.PARALLEL_SHORT_TIMEOUT:d=c.PARALLEL_SHORT_TIMEOUT}d&&bc().a([d],1,4)},Ff=function(){if("html"==z.google_ad_output&&!rb(z)){var a=["39482000","39482001"];bc().a(a,Da,11);a=["39482010","39482011"];bc().a(a,Ea,11)}if(a=
K().b(9)){if("PS"==z.google_ad_handling_experiment||"PL"==z.google_ad_handling_experiment)a=ld,a.K()}else Ef(z.google_ad_handling_experiment)},Gf=function(){Db()!=F()&&$d(4);Ka&&$d(16)};function Hf(){Gf();if(E?1==Me(window):!Me(window))Df(),lf();Ff();var a=j,b="";(a=window.google_async_iframe_id)?a=F().document.getElementById(a):(b="google_temp_span",a=If(b));var c=wf(a);a&&a.id==b&&$c(a);c&&(mf(window,document,window.google_ad_url),sf(window));Ib(window)}
var Jf=function(a){A(Hd,function(b,c){a[b]=window[c]});A(Gd,function(b,c){a[b]=window[c]});A(Id,function(b,c){a[b]=window[c]})},Kf=function(a){s(window.google_eids)&&0!==window.google_eids.length&&$d(64);df(window.google_eids,1);a.eid=cf();var b=bc().oa();0<a.eid.length&&0<b.length&&(a.eid+=",");a.eid+=b};function Lf(a,b,c,d){a=Yd(a,b,c,d);ff(window,document);return a}function Mf(){de()}
function Nf(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=1<d.length?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function Of(){var a=window,b=Nf(document.URL);b.google_ad_override&&(a.google_ad_override=b.google_ad_override,a.google_adtest="on")}
function of(a,b,c){if(a&&(a=b.getElementById(a))&&c&&""!=c.length)a.style.visibility="visible",a.innerHTML=c}
var Pf=function(a,b,c){var d=a.indexOf(b);if(-1===d)return a;b=d+b.length;return a.substr(0,d)+c+a.substr(b)},rf=function(a,b){var c=b.src,d=Pf(c,"/pagead/gen_204?id=prerender",a);d!==c&&(b.src=d)},Qf=function(a,b){b.dff=zd(a).toLowerCase();b.dfs=Ed(a)},Rf=function(a,b){if("html"==z.google_ad_output)try{var c=wd(a,window.top);b.adx=Math.round(c.x);b.ady=Math.round(c.y)}catch(d){b.adx=-12245933,b.ady=-12245933}},Sf=function(a){a.ref=window.google_referrer_url;a.loc=window.google_page_location;if("33895251"==
K().b(7)){var b=Xe(F());a.pasl=b.pasl;a.fasl=b.fasl}b=Db();b=Nd(b);b.url!=a.url&&(b.url!=a.ref&&b.url!=a.loc)&&(a.top=b.url);a.docm=nd()},tf=function(a){var b=Vb(),c=J(b,8),d=J(b,9),e=window.google_ad_section;if(C(window.google_ad_format)){if(4<Xb(b,4,J(b,4)+1)&&!a)return n}else if(rb(window)){if(3<Xb(b,5,J(b,5)+1)&&!a)return n}else{var f=Xb(b,6,J(b,6)+1);if(window.google_num_slots_to_rotate){if($d(1),c[e]="",d[e]="",J(b,12)||Xb(b,12,(new Date).getTime()%window.google_num_slots_to_rotate+1),J(b,12)!=
f)return n}else if(!a&&6<f&&""==e)return n}return i},uf=function(a){var b={};Jf(b);zf(b);tb(b);a&&(Qf(a,b),Rf(a,b));Af(b);Bf(b);Kf(b);Cf(b);Sf(b);b.fu=Zd;return b},If=function(a){var b=window.google_container_id,c=b&&Oc(b)||Oc(a);!c&&(!b&&a)&&(document.write("<span id="+a+"></span>"),c=Oc(a));return c},nf=function(a){var b=(new Date).getTime()-Ke;return jf({dtd:1E4>b?b:"M"},a)},xf=/[+, ]/;window.google_render_ad=Hf;function Tf(){Of();Ve();var a=window.google_start_time;ga(a)&&(Ke=a,window.google_start_time=j);Wd("show_ads.google_init_globals",Lf,Mf);ff(window,document)}Wd("show_ads.main",Yd,Tf);})()

}

/*
     FILE ARCHIVED ON 20:43:07 Jan 30, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 06:08:17 Jul 28, 2026.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  capture_cache.get: 0.57
  load_resource: 72.007
  PetaboxLoader3.resolve: 39.873
  PetaboxLoader3.datanode: 29.665
*/